### ISSUE TITLE
HornSchunck - u and v not calculated

### ISSUE THREAD

**Issue by MartinPerry** [uba/of#2]
In your compute method, `m_u` and `m_v` is not computed, the result of optical flow is zero.

```
void of::HornSchunck::compute()
{
  initialize();

  // Compute derivative images (fx, fy and ft)
  computeDerivativeImages();

  std::size_t size = m_u->getNPixels();

  // Local averages
  double* ubar = new double[size];
  double* vbar = new double[size];

  // Classical Horn-Schunck method iterations
  for(std::size_t it = 0; it < m_maxIterations; ++it)
  {
    computeLocalAvg(ubar, m_u); //<---- where is m_u computed?
    computeLocalAvg(vbar, m_v); //<---- where is m_v computed?
    ... rest of the code
```
Should it be initialized with Lucas-Kanade?

**Comment by uba** [comment]
Hi @MartinPerry!

`m_u` and `m_v` are initialized by `initialize()` method of parent class `OpticalFlow`.
Here: https://github.com/uba/of/blob/master/src/of/OpticalFlow.cpp#L124

````
void of::HornSchunck::compute()
{
  initialize(); // <== It is called here:
  (...)
````

And `computeLocalAvg` is a private method of specialized class `HornSchunck`.
Here: https://github.com/uba/of/blob/master/src/of/HornSchunck.cpp#L87

**Comment by MartinPerry** [comment]
Thank you.. I missed that :)
